export const GET_COUNTRY_LIST = 'GET_COUNTRY_LIST'
export const GET_COUNTRY_LIST_FAILURE = 'GET_COUNTRY_LIST_FAILURE'

export const GET_PROVINCE_LIST = 'GET_PROVINCE_LIST'
export const GET_PROVINCE_LIST_FAILURE = 'GET_PROVINCE_LIST_FAILURE'

export const GET_CITY_LIST = 'GET_CITY_LIST'
export const GET_CITY_LIST_FAILURE = 'GET_CITY_LIST_FAILURE'